spring:
  cloud:
    gateway:
      # 配置route转发规则
      routes:
        - id: order-rote
          uri: lb://services-order
          predicates:
            - Path=/api/order/**
        - id: product-rote
          uri: lb://services-product
          predicates:
            - Path=/api/product/**