#配置OpenFeign
spring:
  cloud:
    openfeign:
      client:
        config:
          # 配置默认超时时间
          default:
            connect-timeout: 1000
            read-timeout: 2000
          # 配置某个具体FeignClient的超时时间
          services-product:    # 微服务名称
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      # 分割web上下文
      web-context-unify: false

feign:
  sentinel:
    enabled: true